// <auto-generated />
namespace Itechart.Survey.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangingModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangingModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201808071701194_ChangingModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
